# Generated by Django 5.1.4 on 2025-06-24 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('adresse', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PDFDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('nom_serveur', models.CharField(max_length=200)),
                ('nombre_page', models.IntegerField()),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='pdfs/')),
                ('processed', models.BooleanField(default=False)),
                ('processing_status', models.CharField(default='pending', max_length=50)),
                ('ai_results', models.JSONField(blank=True, null=True)),
                ('start_page', models.IntegerField(default=1)),
                ('end_page', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shipper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('adresse', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vessel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('flag', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Voyage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_depart', models.DateField()),
                ('date_arrive', models.DateField()),
                ('port_depart', models.CharField(max_length=200)),
                ('port_arrive', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manifest_app.vessel')),
            ],
        ),
        migrations.CreateModel(
            name='ManifestEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produits', models.TextField()),
                ('poids', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('volume', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date', models.DateField()),
                ('page', models.IntegerField(default=1)),
                ('pdf_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manifest_app.pdfdocument')),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manifest_app.vessel')),
                ('voyage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manifest_app.voyage')),
            ],
        ),
    ]
