# Generated by Django 5.1.4 on 2025-06-24 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifest_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfdocument',
            name='nombre_page',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
