# Generated by Django 5.1.4 on 2025-07-11 08:56

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manifest_app", "0003_chatmessage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="manifestentry",
            options={"ordering": ["-date", "-created_at"]},
        ),
        migrations.RemoveField(
            model_name="manifestentry",
            name="voyage",
        ),
        migrations.AddField(
            model_name="manifestentry",
            name="consigne",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="manifest_app.consigne",
            ),
        ),
        migrations.AddField(
            model_name="manifestentry",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="manifestentry",
            name="devise",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="manifestentry",
            name="numero_bl",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="manifestentry",
            name="port_chargement",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="manifestentry",
            name="port_dechargement",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="manifestentry",
            name="quantite",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AddField(
            model_name="manifestentry",
            name="shipper",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="manifest_app.shipper",
            ),
        ),
        migrations.AddField(
            model_name="manifestentry",
            name="unite",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="manifestentry",
            name="valeur",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AlterField(
            model_name="manifestentry",
            name="pdf_document",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="manifest_app.pdfdocument",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="manifestentry",
            name="poids",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AlterField(
            model_name="manifestentry",
            name="volume",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.CreateModel(
            name="Container",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.CharField(max_length=20, unique=True)),
                (
                    "type_container",
                    models.CharField(
                        choices=[
                            ("20GP", "20' General Purpose"),
                            ("40GP", "40' General Purpose"),
                            ("40HC", "40' High Cube"),
                            ("20RF", "20' Refrigerated"),
                            ("40RF", "40' Refrigerated"),
                            ("20OT", "20' Open Top"),
                            ("40OT", "40' Open Top"),
                            ("20FR", "20' Flat Rack"),
                            ("40FR", "40' Flat Rack"),
                            ("20TK", "20' Tank"),
                            ("OTHER", "Autre"),
                        ],
                        default="OTHER",
                        max_length=10,
                    ),
                ),
                ("page", models.IntegerField(default=1)),
                (
                    "poids_brut",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "poids_net",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "poids_tare",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "volume",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "longueur",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "largeur",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "hauteur",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("loaded", "Chargé"),
                            ("empty", "Vide"),
                            ("damaged", "Endommagé"),
                            ("repair", "En réparation"),
                            ("transit", "En transit"),
                            ("delivered", "Livré"),
                        ],
                        default="loaded",
                        max_length=20,
                    ),
                ),
                ("port_chargement", models.CharField(blank=True, max_length=100)),
                ("port_dechargement", models.CharField(blank=True, max_length=100)),
                ("scelle_douane", models.CharField(blank=True, max_length=50)),
                ("scelle_transporteur", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "consigne",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="manifest_app.consigne",
                    ),
                ),
                (
                    "pdf_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="manifest_app.pdfdocument",
                    ),
                ),
                (
                    "shipper",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="manifest_app.shipper",
                    ),
                ),
                (
                    "vessel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="manifest_app.vessel",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="manifestentry",
            name="container",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="manifest_app.container",
            ),
        ),
        migrations.CreateModel(
            name="ContainerContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("produit", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("code_hs", models.CharField(blank=True, max_length=20)),
                (
                    "quantite",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("unite", models.CharField(blank=True, max_length=20)),
                (
                    "poids",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "volume",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "valeur",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("devise", models.CharField(blank=True, max_length=10)),
                ("pays_origine", models.CharField(blank=True, max_length=100)),
                ("marques_numeros", models.TextField(blank=True)),
                (
                    "container",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="containerContent",
                        to="manifest_app.container",
                    ),
                ),
            ],
            options={
                "ordering": ["produit"],
            },
        ),
    ]
