# Generated by Django 5.1.4 on 2025-07-11 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("manifest_app", "0004_alter_manifestentry_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="consigne",
            old_name="adresse",
            new_name="adress",
        ),
        migrations.RenameField(
            model_name="shipper",
            old_name="adresse",
            new_name="adress",
        ),
    ]
