# Generated by Django 5.1.4 on 2025-07-11 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manifest_app", "0005_rename_adresse_consigne_adress_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="containercontent",
            name="devise",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="containercontent",
            name="pays_origine",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
