# Generated by Django 5.1.4 on 2025-07-18 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifest_app', '0006_alter_containercontent_devise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='port_chargement',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='container',
            name='port_dechargement',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='container',
            name='scelle_douane',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='container',
            name='scelle_transporteur',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='containercontent',
            name='code_hs',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='containercontent',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='containercontent',
            name='marques_numeros',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='containercontent',
            name='produit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='containercontent',
            name='unite',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
