# Generated by Django 5.1.4 on 2025-07-24 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifest_app', '0007_alter_container_port_chargement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='notify_party',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Lien vers la catégorie parente (sub-catégorie si renseignée).', null=True, on_delete=django.db.models.deletion.CASCADE, to='manifest_app.category')),
            ],
        ),
        migrations.AddField(
            model_name='containercontent',
            name='categories',
            field=models.ManyToManyField(blank=True, to='manifest_app.category'),
        ),
    ]
