# Generated by Django 5.1.4 on 2025-07-24 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifest_app', '0008_container_notify_party_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='notify_party',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
