# Generated by Django 5.1.4 on 2025-07-24 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifest_app', '0009_alter_container_notify_party'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Lien vers la catégorie parente (sub-catégorie si renseignée).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='manifest_app.category'),
        ),
    ]
